### ISSUE TITLE
Aircontroll

### ISSUE THREAD

**Issue by Orcthanc** [Orcthanc/GamesProjekt2017#1]
Has a few problems:
- [x] You can acc-/deccellerate by pressing sprint in midair
- [x] You always move in the diretion you look

**Comment by ArkanaXXI** [comment]
Accellerating durch Sprinten in der Luft würd ich drin lassen (Jet- /Jumppack und so). Deaccellerating durch loslassen von sprinten sollte allerdings echt raus :|
You always move in the direction you look: Verstehe ich so, dass der nur durchs umschauen, ohne Drücken von Bewegungstasten die Richtung ändert. Wenn dem so ist, dann sollte das definitiv raus.
Es sollte aber definitiv drin bleiben, dass man in der Luft noch Kontrolle über seine Bewegung hat
