### ISSUE TITLE
Bug in Playerbehaviour

### ISSUE THREAD

**Issue by Orcthanc** [Orcthanc/GamesProjekt2017#10]
Jumping near edges can sometimes launches the player in a spiraling motion to the right
Doublejumping commonly does that (ca. 50% (Can someone with less bad luck confirm that value?))

**Comment by LucaTuerk** [comment]
Haven't really noticed it with jumping, but there seems to be some similar issues when walking near edges (Rechtsdrall). There are some small Bridges on NavTest-Scene where this occurs almost allways.

**Comment by Orcthanc** [comment]
@LucaTuerk comment seems to be due to there being an step on the bridge and urelated to the problem

**Comment by Orcthanc** [comment]
Seems to kind of work...
Aaaand I am completely clueless on how this error works, so closing this off for now...
