### ISSUE TITLE
Level

### ISSUE THREAD

**Issue by Orcthanc** [Orcthanc/GamesProjekt2017#5]
- [ ] Basic Layout
- [ ] Start
- [ ] Finish
- [ ] Doors
- [ ] Button
- [ ] Moving Objects

**Comment by LucaTuerk** [comment]
I'm thinking about scrapping the whole tile idea, simply constructing the level in blender should be faster.

**Comment by Orcthanc** [comment]
Ok, but remember, that importing concave models in unity can and will fuck things up
