### ISSUE TITLE
Enemy

### ISSUE THREAD

**Issue by Orcthanc** [Orcthanc/GamesProjekt2017#7]
- [x] Models
- [x] Basic Enemy script
- [x] Flying robot
- [x] Walking robot
- [x] Projectile modell
- [x] Projectile script
- [x] Raycast shot script

**Comment by LucaTuerk** [comment]
Please remove CharacterController-Requirement from Basic Enemy Script, will be using NavMeshAgent for WalkingRobot instead.

**Comment by Orcthanc** [comment]
Done

**Comment by LucaTuerk** [comment]
Start()-Method still tries to get CharacterController-Component.

**Comment by Orcthanc** [comment]
Also done

**Comment by LucaTuerk** [comment]
Done, RayCastShot as Method in Robot.
